---
redis_version: 7.0.6
redis_conf_dir: "/etc/redis"
redis_data_dir: "/opt/redis/data"
redis_log_dir: "/var/log/redis"
redis_port: 6379
redis_cluster_config_dir: "/etc/redis/cluster"
redis_cluster_config_file: "/etc/redis/cluster/nodes.conf"

redis_save:
  - 900 1
  - 300 10
  - 60 10000
redis_stop_writes_on_bgsave_error: "yes"
# the file name for the RDB Backup
redis_db_filename: "dump.rdb"

redis_appendonly: "no"
redis_appendfilename: "appendonly.aof"

# CLIENTS
# Max connected clients at a time
redis_maxclients: 10000

# NETWORKING/CONNECTION OPTIONS
redis_bind: "{{ ansible_ssh_host }}"

redis_conf_file_location: /etc/redis
redis_runtime_directory: redis

redis_slave_read_only: "yes"
